version: "3.8"

services:
  urlshortener:
    build:
      context: ./
      dockerfile: release.Dockerfile
    container_name: url-shortener
    restart: always
    env_file:
      - app/dev.env
    volumes:
      - "./app:/app"
    ports:
      - "8080:8080"