on:
  push:
    branches:
      - master
     
name: Terraform Apply

jobs:
        
  provision-vpc:
    name: provisionvpc
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TF_USER_AWS_SECRET }}
        aws-secret-access-key: ${{ secrets.TF_USER_AWS_KEY }}
        aws-region: ${{ secrets.REGION }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    
    - name: Terraform Apply
        id:   apply
        run: |
          cd terraform/
          terraform init
          terraform validate
          terraform plan 


#terraform apply -auto-approve

    # - name: Terraform plan
    #   shell: pwsh
    #   run: |
    #     terraform init -backend-config="./terra/terraform_state.tfvars"
    #     terraform plan -var-file="./tfvars/terraform.tfvars"
        
    # - name: Terraform apply
    #   shell: pwsh
    #   run: |
    #     terraform apply -auto-approve -var-file="./tfvars/terraform.tfvars"   